name: Bug report 🐛
description: If something isn't working as expected 🤔.
labels: status/needs-verification

body:
  - type: input
    id: nexus-version
    attributes:
      label: Nexus Version
      description: Provide the Nexus version that you are using.
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.3.9
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        ⚠️  This is the most important part of the report ⚠️
        Please take some time in showing us the complete details on how to reproduce the bug.
        If necessary, please provide a Github repository to demonstrate your issue.
    validations:
      required: true
