name: Feature request 🚀
description: I have a suggestion (and may want to implement it 🙂)!
labels: type/feature-request

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear description of what problem you are trying to solve and how would you want it to be solved.
    validations:
      required: true
