name: Prune GitHub Actions Caches

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types:
      - closed

jobs:
  prune:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run prune-cache script
        run: |
          bin/prune-cache ${{ env.REPO }} ${{ env.PR_BRANCH }} ${{ env.SCHEDULE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_BRANCH: ${{ github.event_name == 'pull_request' && format('--pr-branch {0}', github.event.pull_request.number) || '' }}
          SCHEDULE: ${{ github.event_name == 'schedule' && '--schedule' || '' }}
