name: Static Code Analysis

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    branches:
      - 1.x

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.2
          - 8.3

    name: Static Code Analysis
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Get composer cache directory
        id: cache-dir
        run: |
          echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.cache-dir.outputs.COMPOSER_CACHE_DIR }}
          key: ${{ github.workflow }}-PHP_${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}-${{ github.run_id }}
          restore-keys: |
            ${{ github.workflow }}-PHP_${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}-
            ${{ github.workflow }}-PHP_${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer update --ansi

      - name: Check - file permissions
        run: bin/check-file-permissions

      - name: Check - PHP-CS-Fixer
        run: composer cs:check

      - name: Check - PHPStan
        run: composer phpstan:check
